name: Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v2
      - name: Setup dependencies
        run: |
          uv sync --all-extras
          uv pip install -e .
      - name: Run tests
        run: |
          set -o pipefail
          uv run pytest --cov=thucia --cov-report=term --cov-report=html 2>&1 | tee coverage.txt
          # Display coverage report in the GitHub Actions summary
          cat coverage.txt
          echo '### Coverage Report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/
